#!/usr/bin/php -q
<?php

putenv('TZ=America/Denver');

$options = getopt('pd');

if (isset($options['d'])) {
  $debug = 1;
} else {
  $debug = 0;
}
if (isset($options['p'])) { 
  $varnishstat = $options['p'];
} else {
  $varnishstat = '/usr/bin/varnishstat';
}

if ($debug) {
  print "Command line arguments:\n";
  foreach($options as $key=>$value) {
    print "  $key -> $value\n";
  }
  print "\n";
}

$command = "$varnishstat -1 2>&1";

if ($debug) {
  print "Command to execute:\n";
  print "  $command\n";
}

exec($command, $output);
if (preg_match("/No such file or directory/", join($output), $matches)) {
  print "Sorry, but $varnishstat does not exist, are you sure that varnish is installed and that's the right path?\n";
  exit(2);
}

$metrics = array();
foreach($output as $line) {
  if (preg_match("/^(\S+?)\s+?(\d+?)\s+?/", $line, $matches)) {
    $key = $matches[1];
    $value = $matches[2];
    if ($key === 'client_conn') {
        $metrics['client_conn'] = $value;
    } else if ($key === 'client_req') {
        $metrics['client_req'] = $value;
    } else if ($key === 'cache_hit') {
        $metrics['cache_hit'] = $value;
    } else if ($key === 'cache_miss') {
        $metrics['cache_miss'] = $value;
    } else if ($key === 'n_backend') {
        $metrics['n_backend'] = $value;
    } else if ($key === 's_sess') {
        $metrics['s_sess'] = $value;
    } else if ($key === 's_req') {
        $metrics['s_req'] = $value;
    } else if ($key === 'n_wrk') {
        $metrics['n_wrk'] = $value;
    } else {
        continue;
    }
  }
}

if ($debug) {
  print "Parsed varnishd stats results:\n";
  foreach($metrics as $var=>$val) {
   print "  $var -> $val\n";
  }
  print "\n";
}

if (isset($metrics['cache_hit']) && isset($metrics['cache_miss'])) {
  $metrics['total_caches'] = $metrics['cache_hit'] + $metrics['cache_miss'];
  $metrics['cache_hit_rate'] = round($metrics['cache_hit']/$metrics['total_caches']*100, 2);
  $metrics['cache_miss_rate'] = round($metrics['cache_miss']/$metrics['total_caches']*100, 2);
} else {
  print "VARNISH CRITICAL! Cannot parse metrics. | \n";
  exit(2);
}

if ($metrics['n_backend'] < 1) {
  $exitstring = "VARNISH CRITICAL! No backends running. | ";
  $exitcode = 2;
} elseif ($metrics['cache_miss_rate'] > $metrics['cache_hit_rate']) {
  $exitstring = "VARNISH WARNING! Cache miss rate is " . $metrics['cache_miss_rate'] . "%. | ";
  $exitcode = 1;
} else {
  $exitstring = "VARNISH OK. | ";
  $exitcode = 0;
}

foreach ($metrics as $var => $val) {
  $exitstring .= "$var=$val,";
}

print "$exitstring\n";
exit($exitcode);

function usage() {
  print "usage: check_varnish -h <host> -p <port> [ -s <secretfile> ] [ -v </path/to/varnishstat> ] [-h]\n";
  print "\n";
  exit(2);
}

?>
